yearn/yearn-finance

- internals/webpack/webpack.prod.babel.js
when user installs pwa app on mobile, it says React BP under the icon (from the React BoilerPlate being used).
This fixes it by replacing the description with yearn, should also fix it on splash screen
> fix: manifest description

- app/components/ConnectButton/index.js
- app/components/CoverCard/index.js
- app/containers/Vaults/index.js
This PR adds/changes the following:
- Change Launch app to Connect wallet on Top bar.
- Add linear progress feedback when wallet is connected and vault list is empty.
- Use Circular loader for cover cards when loading data
> fix: add loading feedback on vaults

- app/containers/ConnectionProvider/services.js
**Background**
The Lattice1 is GridPlus' next generation Ethereum-focused programmable hardware wallet. It is an always-online device with physically separated secure compute and Linux general compute environments. For more information, see https://gridplus.io/
**About this PR**
This PR adds the Lattice1 to the list of available wallets via Blocknative Onboard v1.18.0, which is currently used by Yearn and fully supports the Lattice1.
The Lattice1 can load smart contract ABIs so that interactions with your contracts are human-readable on the touchscreen which is drawn using the secure compute environment. This can help prevent man-in-the-middle attacks even when your computer is compromised. You can learn more about this functionality in [this blog …
> feat: add lattice1 support

- app/components/Vault/index.js
yearn API isn't reporting a correct apy for v2 vaults. until we figure
out what is the issue we need to prevent user from seeing wrong
calculations.
> fix(v2-vaults): display N/A for apy (tmp change)

- app/components/RoundedInput/index.js
- app/components/VaultControls/index.js
- Prevents user inputs that are more than the max allowed value the field supports, for vaults.
> Vault Input Validation

- package.json
- yarn.lock
This resolves an issue with the Lattice1 integration, which is
currently broken on the live yearn site.
Erry day
> Bumps bnc-onboard to 1.19.0

- app/components/ContractStatisticsModal/index.js
Reading the values of the vault modals is difficult due to them not being formatted to local reading styles. Showing the full value to minimal dust values only makes the experience of using these dashboards more difficult.
This also adds getPricePerFullShare to scaleAllowList as that value should be scaled.
> fix: format vault model to human readable locality

- app/components/Vault/index.js
- app/containers/App/selectors.js
- Temporary fix for:
>  Manually update displayed USDN APY for now since we're pulling 80% for backscratcher
Add disclaimer in drop-down menu for USDN as well like we had for DAI after hack. Something like 80% of USDN CRV yield is deposited to yveCRV. APY of ~20% is accurate after accounting for this.
from https://github.com/iearn-finance/iearn-finance/issues/247
Note: Remove after a permanent fix is implemented.
> fix: base apy for usdn vault

- app/components/Vault/index.js
- app/containers/Vaults/index.js
@x48-crypto This should resolve #183 
* Each vault is now associated with a URL address e.g. `/vaults/0x5dbcF33D8c2E976c6b560249878e6F1491Bca25c`
* Expanding each vault also scrolls to center of screen `el.scrollIntoView({ behavior: 'smooth', block: 'center' })`
A potential future enhancement would be to support this for the `backscratcher` vault.
> feat: vault links

- app/components/VaultControls/index.js
Disable a deposit if the value entered is 0, which stops a user from depositing 0 into a vault and potentially spending hefty gas fees on an empty deposit. Namely, `depositsDisabled` is updated with an additional `if` statement that checks `depositGweiAmount` is not 0.
This fix is true for any v2 vault and can help make sure users don't spend nominal (10-20 USD) to thousands of USD on a contract that deposits a 0 value. 
Note that this resolves [issue #252 from iearn-finance repo](https://github.com/yearn/iearn-finance/issues/252), which states the issue actually occurs for v2 and not v1. Thus, issue #252 in `iearn-finance` can be moved to `yearn-finance` and resolved with this fix.
1. Go to: "Invest" > "Vault" (from v2 homepage)
2. Click on any vault and click "Deposit"
- Example (before …
> fix: disable vault deposit button if value is 0

- .github/workflows/check-payment-code.yml
github action to help avoid missing payment related modifications in commits,
it's no silver bullet of course but could help
It posts a comment on the PR issue if PR diff contains:
- any constant
- web3 related code (cacheSend etc)
- any ethereum address (it fetches from yearn API to check if it's  a known vault or token address and displays a warning if not found)
action url: https://github.com/patcito/check-keywords-in-diff
> feat: github action that checks diff for payment code

- app/components/VaultControls/index.js
I've just noticed this behaviour when trying to zap into yvBOOST-ETH v2 vault. Any numbers between 1 and 10 as the deposit amount deactivated the Deposit button. Everything below 0 and over 10 was fine :joy: 
I guess it's because we're returning `depositGweiAmount` as a string from the react state and then the comparison is based on two strings because `sellToken.balanceRaw` is also a string.
Fixed the yvBOOST deposit button for now by using `BigNumber` comparisons.
> Fix: deposit button for yvBOOST-ETH v2 vault

- app/components/Vault/index.js
- Remove APY tooltip on new endorsed vaults.
> fix: remove APY tooltip on new endorsed vaults [WEB-402]

- app/components/Vault/index.js
should save us up to 400 re-rendering on load
this commit is back ported from #366 in case it doesn't get merged
> fix: don't render VaultControls when hidden

- app/components/VaultControls/index.js
issue#110: Vaults UI currently rounds a user's holdings up, but this leads them to potential issues where instead of clicking "max", they manually type in more than they actually hold in their wallet when trying to deposit to vaults and get an error, but they don't know why.
For example: If you max deposit 6.666Tokens, it will be 6.67.
6.666 < 6.67.
So the deposit action will fail.
issue#111: Yearn v2 UI currently shows two decimals for "max", and it would be helpful to show more than this.
The wallet/vault balance should show 5 decimals, and round down in the UI instead of up.
Two issue are connected with the function usage of BigNumber.toFixed().
its reference book is here:
https://mikemcl.github.io/bignumber.js/#toFix
There are some usage samples in the reference book:
x = 3.456
y = …
> fix: improve handling of decimals in UI

- app/components/Vault/index.js
- Deprecates the use of `https://stkpowy01i.execute-api.us-west-1.amazonaws.com/prod/protocol/jar/yvboost-eth/performance` in favor of `https://stkpowy01i.execute-api.us-west-1.amazonaws.com/prod/protocol/pools` for fetching yvboost-eth APY.
> fix: yvBoostEth apy [WEB-474]

- app/components/Footer/index.js
Copy-and-pasting the link into Discord results in an error due to the trailing slash.
> fix: Discord link

- app/containers/Zapper/saga.js
- app/drizzle/store/DrizzleContract.js
- Add support for legacy transactions when metamask v10 + hw wallets errors out trying to use EIP-1559 type 2 transactions.
> fix: handle unsupported EIP-1559 network error [WEB-704]

- app/containers/Zapper/saga.js
- Deprecate zapper's vault-stats endpoint in favor of new token-market-data
> refactor: deprecate vault-stats zapper endpoint [WEB-727]

- app/components/Vault/index.js
- app/containers/App/reducer.js
- app/containers/Vaults/saga.js
- Removed old API dependency in as unobtrusive way as possible
- Confirmed all vaults from yearn.finance are present 
- Confirmed all APY and vault assets are correct
- Confirmed vault ordering is correct (one minor caveat is yvBOOST and yveCRV order are switched, but I actually think this is fine.. otherwise order is perfect. can change this if desired)
- Confirmed all special vault display names and icon URLs are correct (there are two special vault icon overrides that rely on yearn-assets/icons rather than multichain. everything else uses multichain)
> refactor: remove old API dependency
