- app/global-styles.js
homepage was overflowing, #app overflow-y property was causing the issue.
overflow-y: visible fixes the issue
> fix: homepage overflowing

- .github/workflows/productionDeploy.yml
- app/global-styles.js
> feat: invalidate more cloudfront dists in cicd

- .eslintrc.js
- .github/workflows/productionDeploy.yml
- app/global-styles.js
- package.json
> feat(.eslintrc.js): change warning to 2 so it errors

- app/components/ConnectButton/ConnectedAccount.js
- app/components/ConnectButton/index.js
- app/components/Navbar/index.js
> fix: make nav responsive

- app/components/ConnectButton/ConnectedAccount.js
- app/components/ConnectButton/index.js
- app/components/Navbar/FlyingMobileMenu.js
- app/components/Navbar/index.js
> Fix: nav on mobile

- app/components/CoverDetailCardBuy/index.js
- app/components/CoverDetailCardSell/index.js
- app/components/CoverProtocolDetail/index.js
- app/components/CoverTallCard/index.js
- app/containers/Cover/index.js
> fix: make cover details responsiveish

- app/containers/ConnectionProvider/index.js
- app/containers/ConnectionProvider/services.js
> fix: wallet connect connect and move up

- app/components/Navbar/menuLinks.js
> feat: update navbar to have a yield dropdown with vaults and earn

- app/components/SplashScreen/Hero/index.js
> fix: splash screen img bg on mobile

- app/components/SplashScreen/Hero/index.js
- app/components/Vault/columns.js
- app/components/Vault/columnsDev.js
- app/components/VaultsNavLinks/index.js
- app/containers/Vaults/index.js
> fix: make vault table a bit more responsive

- app/components/Navbar/index.js
- Add better responsiveness to the header alignment.
> Fix header alignment

- app/components/RoundedInput/index.js
- Add red border feedback to vaults inputs when invalid amount is entered.
- Fix decimal regex validation.
> fix: add validation feedback

- app/components/RoundedInput/index.js
- Quick fix for removing red border when no value prop is sent to input component.
> fix: remove error feedback on edgecase

- app/components/TokenIcon/index.js
> fix: ticking vaults

- app/components/CreamModal/index.js
- Fix cream repay edge case so that no dust is left when max amount set.
> fix: no dust on repay max amount

- app/index.html
> fix: no cache

- app/components/Vault/index.js
- Fix merged issue in backscratcher info.
> fix: backscratcher info

- README.md
Just a little documentation on how to add custom tokens for the mainnet-fork
> fix: updated readme to add custom tokens brownie

- app/containers/Cover/saga.js
- app/utils/cover.js
- Quick fix to get cover page working by removing cover tokens with no claim pool.
> fix: remove cover tokens with no claim pool

- app/components/SplashScreen/Backscratcher/index.js
- app/components/SplashScreen/index.js
- app/containers/Cover/index.js
- app/containers/Main/index.js
- Fix splash centering.
- Fix sphere brightness.
> fix: centering issues and sphere brightness

- app/components/Navbar/MobileMenu.js
- app/components/Navbar/index.js
- package.json
- yarn.lock
- Add new UI changes for mobile menu.
> feat: new mobile menu UI

- app/components/Navbar/MobileMenu.js
- Fixes nested item color on mobile menu
> fix: menu nested items color

- app/components/ConnectButton/ConnectedAccount.js
- app/components/ConnectButton/index.js
- app/components/Navbar/MobileMenu.js
- Add wallet connect button to mobile menu.
> feat: add mobile wallet connect

- app/components/Box/index.js
- app/components/RoundedInput/index.js
- app/components/Vault/backscratcherColumns.js
- app/components/Vault/index.js
- app/components/VaultControls/index.js
- app/containers/Vaults/index.js
- Add the base mobile view for vaults page.
> feat: mobile view for vaults page

- README.md
> fix: Update README.md to fix type-o

- app/components/Vault/backscratcherColumns.js
- app/containers/Vaults/index.js
- Better responsiveness for some screen widths.
> fix: vaults page responsiveness

- app/components/VaultControls/index.js
- Add responsiveness to backscratcher claim button.
> fix: responsive backscratcher claim button

- app/components/Vault/index.js
- app/containers/Vaults/index.js
- Display vault alias in a tooltip when hover over vault icon and name at vaults page.
> refactor: add vault alias tooltip

- app/components/MigrateVault/index.js
- app/containers/Vaults/saga.js
- app/containers/Vaults/selectors.js
- Display migration button in the target v2 vault.
> feat: add migration button to target vault

- app/containers/Vaults/index.js
- Fix the sorting for vaults by total assets.
> fix: vaults total assets sorting

- app/components/MigrateVault/index.js
- app/containers/Vaults/saga.js
- app/containers/Vaults/selectors.js
Reverts yearn/yearn-finance#204
> revert: revert "feat: add migration button to target vault"

- app/components/Vault/index.js
- app/components/VaultControls/index.js
- temp remove migration feature
> fix: temp remove migration feature

- app/components/Vault/index.js
- app/components/VaultControls/index.js
- Disable vault deposits on emergency shutdown
> feat: disable vault deposits on emergency shutdown

- app/containers/App/selectors.js
- Display only endorsed vaults
> refactor: filter all endorsed vaults

- app/components/CoverCards/index.js
- app/containers/Cover/saga.js
- Resolves cover cards that are always in loading state.
> fix: resolve cover loading cards

- app/components/Vault/index.js
- app/containers/Vaults/index.js
- Fix sorting vaults by growth and by available to deposit.
- Temporary fix for DAI v1 APY to use oneWeekSample.
> fix: vault sorting bugs and dai v1 apy

- app/components/ButtonFilled/index.js
- app/components/MigrateVault/index.js
- app/components/Vault/index.js
- app/components/VaultControls/index.js
- app/containers/Vaults/migrationWhitelist.example
- app/containers/Vaults/migrationWhitelist.json
- app/containers/Vaults/selectors.js
> feat: YFI migration implementation

- app/components/ButtonFilled/index.js
- Changes button outline color to the standard color used in theme.
> fix: standard button outline color

- app/components/Vault/index.js
- app/global-styles.js
Just a little fix for:
- Icon size
- Icon margin
- SHOW font weight
- SHOW margin
- VAULT height
> fix: hidden vault style

- app/components/BackscratcherClaim/index.js
- app/components/ButtonFilled/index.js
- app/components/RoundedInput/index.js
- app/components/Vault/index.js
- app/components/VaultControls/index.js
- app/global-styles.js
Flips the withdraw with approve/deposit buttons in normal vaults.
Fixes style in buttons and select/input
> fix: flip vault buttons and style

- app/containers/Vaults/migrationWhitelist.json
> feat: enable weth migration

- app/components/Vault/index.js
- app/global-styles.js
Fixes some of the vault styles and pickle styles
> fix: vault open line

- app/components/VaultControls/index.js
- app/containers/Zapper/actions.js
- app/containers/Zapper/constants.js
- app/containers/Zapper/reducer.js
- app/containers/Zapper/saga.js
As suggested by @dudesahn 
tokens supported are eth, wbtc, dai, usdc, usdt
> feat: allow zapping out of vaults directly

- app/components/Vault/index.js
- app/components/VaultControls/index.js
Should fix this bug https://github.com/yearn/yearn-finance/pull/255#issuecomment-817387958
> fix: zapout styling on mobile

- app/components/Vault/index.js
as requested by @dudesahn using https://github.com/yearn/yearn-finance/blob/develop/app/containers/Vaults/migrationWhitelist.json
> feat: hide migrated vaults with empty balance

- app/components/VaultControls/index.js
> Fix typo pickle

- app/containers/Zapper/saga.js
> fix: set default slippage

- app/components/Vault/index.js
- app/components/VaultControls/index.js
- app/containers/Vaults/saga.js
- Fix withdraw all issue from v2 migratable vaults
> fix: withdraw all from v2 vaults

- .github/workflows/check-payment-code.yml
action itself was fixed upstream
> fix: make action name to be more relevant (minor)

- app/containers/Vaults/saga.js
0x03403154afc09Ce8e44C3B185C82C6aD5f86b9ab
0xb4D1Be44BfF40ad6e506edf43156577a3f8672eC
0xBacB69571323575C6a5A3b4F9EEde1DC7D31FBc1
Withdraw All/Withdraw: 2M gas
Migrate: 2.8M gas
> refactor: set gas limit to 2.8M for migrateAll and 2M for all crvAAVE vaults

- app/components/VaultControls/index.js
> fix: disable yvboost

- app/components/VaultControls/index.js
- Enable regular yvboost deposits (no zaps)
> fix: enable yvboost regular deposits

- app/containers/Zapper/saga.js
- Fetch token balances through new zapper token balances endpoint
> refactor(zapper): update balances endpoint [WEB-158]

- app/components/VaultControls/index.js
This reverts commit b9415518ee735a9606c3ba876302fecaae560889.
> refactor: revert "refactor: temporarily disable eth vaults" [WEBE-170]

- app/components/BackscratcherClaim/index.js
- app/containers/App/saga.js
- Fix claimable amount of 3crv on backscratcher
> fix: backscratcher claimable reward [WEB-199]

- app/components/Vault/index.js
- Update deprecated pickle API endpoints
> fix: update pickle API endpoint [WEB-196]

- app/components/VaultControls/index.js
- app/containers/Zapper/saga.js
Show better message when zapper call fails.
> feat: show better message when zapper fails

- app/components/Vault/index.js
- app/containers/Vaults/index.js
- app/containers/Vaults/saga.js
- Refactor to use APY from new API endpoint, merging data to old schema.
> refactor: migrate apy from new api endpoint [WEB-355]

- app/components/Vault/index.js
- app/containers/Vaults/saga.js
- Refactors apy error handling to new api schema
- Rename to Gross APR on tooltips
> refactor: apy error handling and naming

- app/components/Vault/index.js
- app/components/VaultControls/index.js
- app/containers/Zapper/saga.js
- Use classic WETH logo on sell token select
- ETH as default sell token on _ETH_ vaults
- Show ETH on _available to deposit_ instead of WETH
> fix: polish eth vault [WEB-368]

- app/containers/ConnectionProvider/index.js
- Add modal message to ask user to change to correct network when users wallet is not on eth mainnet.
> feat: validate wallet network

- package.json
- yarn.lock
- Update Blocknative onboard to newest version for support of new breaking changes on newest browser versions for ledger wallet.
> refactor: update blocknative onboard [WEB-406]

- app/components/Vault/index.js
- app/containers/Vaults/saga.js
Edit: fixed Not sure how to truncate keep_crv amount, let me know and I will update the PR. //cc @dudesahn 
I've also included the fix for WEB-408 as they both rely on the same fix.
> fix: show keep_crv fee [WEB-413] and [WEB-408]

- app/components/VaultControls/index.js
Reverts yearn/yearn-finance#379
> revert: revert "fix: improve handling of decimals in UI"

- app/components/Navbar/menuLinks.js
> feat: add link to menu [WEB-486]

- app/components/VaultControls/index.js
- Enables yvBoost zapIn functionality.
> feat: enable yvBoost zapIn [WEB-545]

- app/containers/ConnectionProvider/index.js
- app/containers/ConnectionProvider/services.js
- package.json
- yarn.lock
- Updates blocknative onboard.js to latest release.
- Add support for Rabby wallet.
> feat: update blocknative onboard and add rabby wallet support

- package.json
- yarn.lock
- Update to latest onboard version that fixes small bugs for various wallets.
> chore: update onboard version

- package.json
- yarn.lock
> chore: update web3

- app/containers/Zapper/saga.js
- app/global-styles.js
- Update balances on account change
- Fix styles on account change modal for hw wallets
> fix: update on account change

- app/components/VaultControls/index.js
- Fix broken zap token icons due to zapper's images migrated to CDN.
> fix: zap token icons [WEB-726]

- app/containers/ConnectionProvider/services.js
- package.json
- yarn.lock
- Add MEW wallet support.
- Fix multiple prompts for network switch bug.
> feat: mewwallet support [WEB-814]

- app/containers/Vaults/migrationWhitelist.json
- Add old yfi vault to migration whitelist
> feat: new yfi vault migration [WEB-956]

- app/components/TokenIcon/index.js
- app/components/VaultControls/index.js
- Use new yearn-assets multichain path
> refactor: migrate yearn-assets to multichain path [WEB-989]

- app/components/VaultControls/index.js
- Temporarily disable curve usdm vault deposits
> feat: disable curve usdm deposits

- app/containers/Vaults/migrationWhitelist.json
- Change to a more clear migration message for USDC vault
> refactor: change migration message
